import { useState } from 'react'
import './App.css'

function App() {
  const [quote, setQuote] = useState("");
  const quotes = [
  "Believe in yourself.",
  "Stay hungry, stay foolish.",
  "Dream big and dare to fail.",
  "Consistency beats motivation.",
  "Work hard in silence.",
  "Make it happen.",
  "Push yourself every day.",
  "Success needs discipline.",
  "Do it with passion.",
  "Never stop learning.",
  "Focus on progress, not perfection.",
  "Small steps matter.",
  "Your only limit is you.",
  "Action creates confidence.",
  "Start before you're ready.",
  "Discipline equals freedom.",
  "Growth begins outside comfort.",
  "Stay positive, work hard.",
  "Turn pain into power.",
  "Think big, act bigger.",
  "Be stronger than excuses.",
  "Hard work compounds.",
  "Effort never betrays.",
  "Learn from failure.",
  "Be obsessed with improvement.",
  "Make yourself proud.",
  "Chase progress, not applause.",
  "Stay consistent.",
  "Be fearless in pursuit.",
  "Mindset is everything.",
  "Your future needs you.",
  "Rise and grind.",
  "Create your own sunshine.",
  "Dream it. Do it.",
  "Don't wait. Create.",
  "Build better habits.",
  "Work until it works.",
  "Stay focused.",
  "Make today count.",
  "Success loves preparation.",
  "Confidence comes from action.",
  "Improve 1% daily.",
  "Done is better than perfect.",
  "Stay disciplined.",
  "Trust the process.",
  "Learn. Apply. Repeat.",
  "Take the risk.",
  "Make discipline a lifestyle.",
  "Be your own hero.",
  "Start small. Finish strong.",
  "Patience builds greatness.",
  "Hard days build strong minds.",
  "Stay sharp.",
  "Keep moving forward.",
  "Turn dreams into plans.",
  "Failure is feedback.",
  "Stay humble, hustle hard.",
  "Make excuses or make progress.",
  "Results need effort.",
  "Think long term.",
  "Show up every day.",
  "Build your vision.",
  "Energy flows where focus goes.",
  "Win the morning.",
  "Stay relentless.",
  "Master the basics.",
  "Act with purpose.",
  "Don’t quit early.",
  "Habits shape destiny.",
  "Stay committed.",
  "Make consistency attractive.",
  "Learn faster.",
  "Take ownership.",
  "Outwork your yesterday.",
  "Be unstoppable.",
  "Think positive.",
  "Turn fear into fuel.",
  "Level up daily.",
  "Make hard choices.",
  "Stay dedicated.",
  "Keep growing.",
  "Do something today.",
  "Invest in yourself.",
  "Stay patient.",
  "Success is earned.",
  "Dream without limits.",
  "Work smart and hard.",
  "Keep showing up.",
  "Be bold.",
  "Create momentum.",
  "Push past limits.",
  "Stay resilient.",
  "Make progress daily.",
  "Challenge yourself.",
  "Keep faith.",
  "Stay determined.",
  "Earn your success.",
  "Improve every day.",
  "Believe. Build. Become."
  ];
  function generateQuote(){
    setQuote(quotes[Math.floor(Math.random()*quotes.length)]);
  }
  return (
      <div>
        <h1>RANDOM QUOTE GENERATOR</h1> <br />
        <button onClick={generateQuote}>Click</button><br /><br />
        <h1 className='color-change'>{quote}</h1>
      </div>
  )
}

export default App
